version: '3'

services:
  broker-servce:
    build:
      context: ./broker/
      dockerfile: broker-service.Dockerfile
    restart: always
    ports: 
    - "8080:80"
    deploy:
      mode: replicated
      replicas: 1